//! The PATH shim — Layer 1.
//!
//! Wrappers for the commands that can lose work, prepended to the **agent**
//! process environment only, never the user's terminal (D7).
//!
//! **This is a guard, not the floor.** It is bypassable by absolute path, and
//! inside the sandbox the agent can call `/usr/bin/git` directly. What it buys
//! is that accidents fail loudly with a legible reason — which is most of what
//! actually goes wrong. bwrap is what makes the filesystem guarantee real.
//!
//! Generated into local state at startup rather than committed (D8), so a stale
//! checkout can never leave an out-of-date guard on `PATH`.

use std::io;
use std::path::{Path, PathBuf};

/// Commands worth wrapping. Anything not listed resolves normally.
pub const WRAPPED: &[&str] = &["git", "gh", "rm", "sudo"];

/// Where the wrappers are written. Local state, never committed.
pub fn dir(data_home: &Path) -> PathBuf {
    data_home.join("githud/shim")
}

/// Write the wrappers, replacing any that exist.
pub fn install(data_home: &Path) -> io::Result<PathBuf> {
    let dir = dir(data_home);
    std::fs::create_dir_all(&dir)?;

    for name in WRAPPED {
        let path = dir.join(name);
        std::fs::write(&path, script(name))?;
        set_executable(&path)?;
    }

    Ok(dir)
}

#[cfg(unix)]
fn set_executable(path: &Path) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt as _;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))
}

#[cfg(not(unix))]
fn set_executable(_path: &Path) -> io::Result<()> {
    Ok(())
}

/// `PATH` for the agent, with the shim first.
///
/// The shim directory is dropped from the inherited `PATH` first, so repeated
/// starts cannot stack duplicates.
pub fn agent_path(data_home: &Path, inherited: &str) -> String {
    let shim = dir(data_home);
    let shim_str = shim.to_string_lossy();
    let rest: Vec<&str> = inherited
        .split(':')
        .filter(|p| !p.is_empty() && *p != shim_str)
        .collect();
    std::iter::once(shim_str.as_ref())
        .chain(rest)
        .collect::<Vec<_>>()
        .join(":")
}

/// The wrapper script for one command.
///
/// Default-deny in shape: each script enumerates what is refused, and anything
/// unrecognised falls through to the real binary. That is the honest reading —
/// a shim cannot enumerate every dangerous invocation, which is precisely why
/// it is not the floor.
fn script(name: &str) -> String {
    let header = "\
#!/usr/bin/env bash
# Generated by GIT HUD. Do not edit — rewritten at every start.
# Layer 1 of the guardrails (D7). A guard, not the floor: bwrap is the floor.
set -euo pipefail

deny() {
  echo \"GIT HUD blocked: $*\" >&2
  echo \"This operation can lose work, so the agent is not allowed to run it.\" >&2
  echo \"Run it yourself in the Terminal pane if you mean it.\" >&2
  exit 97
}

# Resolve the real binary, skipping this shim.
real() {
  local self me
  self=$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)
  while IFS= read -r -d: me; do
    [ -z \"$me\" ] && continue
    [ \"$me\" = \"$self\" ] && continue
    if [ -x \"$me/$1\" ]; then echo \"$me/$1\"; return 0; fi
  done <<< \"${PATH}:\"
  echo \"\"; return 1
}
";

    let body = match name {
        "git" => GIT_BODY,
        "gh" => GH_BODY,
        "rm" => RM_BODY,
        "sudo" => SUDO_BODY,
        _ => "exec \"$(real \"$(basename \"$0\")\")\" \"$@\"\n",
    };

    format!("{header}\n{body}")
}

const GIT_BODY: &str = r#"
PROTECTED_RE='^(main|master|dev|develop)$'
sub="${1:-}"

case "$sub" in
  push)
    for a in "$@"; do
      case "$a" in
        --force|-f|--force-with-lease|--force-if-includes)
          deny "git push $a" ;;
      esac
    done
    # A push naming a protected branch, in any refspec position.
    for a in "$@"; do
      ref="${a##*:}"; ref="${ref#+}"
      if [[ "$ref" =~ $PROTECTED_RE ]]; then
        deny "git push to $ref"
      fi
    done
    # A bare `git push` inherits the current branch; refuse if that is shared.
    # Default-deny: if the branch cannot be determined, the guard cannot say the
    # push is safe, so it does not pretend to.
    if [ "$#" -eq 1 ]; then
      cur=$("$(real git)" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
      if [ -z "$cur" ] || [[ "$cur" =~ $PROTECTED_RE ]]; then
        deny "git push from ${cur:-an undeterminable branch}"
      fi
    fi
    ;;
  merge)  deny "git merge" ;;
  rebase) deny "git rebase" ;;
  reset)
    for a in "$@"; do
      [ "$a" = "--hard" ] && deny "git reset --hard"
    done
    ;;
  commit)
    for a in "$@"; do
      [ "$a" = "--amend" ] && deny "git commit --amend"
    done
    ;;
  branch)
    for a in "$@"; do
      case "$a" in
        -D|--delete|-d) deny "git branch delete" ;;
      esac
    done
    ;;
  config)
    # Writing global config would outlive the project and the sandbox.
    for a in "$@"; do
      case "$a" in
        --global|--system) deny "git config $a" ;;
      esac
    done
    ;;
  clean)
    for a in "$@"; do
      [ "$a" = "-x" ] || [ "$a" = "-fdx" ] && deny "git clean $a"
    done
    ;;
esac

exec "$(real git)" "$@"
"#;

const GH_BODY: &str = r#"
sub="${1:-}"
obj="${2:-}"

# The token is reachable (D19), so this catches accidents, not injection.
case "$sub $obj" in
  "pr merge")     deny "gh pr merge" ;;
  "pr close")     deny "gh pr close" ;;
  "repo delete")  deny "gh repo delete" ;;
  "repo archive") deny "gh repo archive" ;;
  "release delete") deny "gh release delete" ;;
  "auth logout")  deny "gh auth logout" ;;
  "auth token")   deny "gh auth token" ;;
  "secret set")   deny "gh secret set" ;;
esac

case "$sub" in
  api)
    for a in "$@"; do
      case "$a" in
        -XDELETE|--method=DELETE) deny "gh api DELETE" ;;
        DELETE) deny "gh api DELETE" ;;
      esac
    done
    ;;
esac

exec "$(real gh)" "$@"
"#;

const RM_BODY: &str = r#"
# Deleting tracked files is how work disappears. The vault rule applies:
# never delete, surface it.
for a in "$@"; do
  case "$a" in
    -rf|-fr|-Rf|-fR) deny "rm $a" ;;
    /|/*)
      case "$a" in
        /tmp/*) : ;;
        *) deny "rm outside the project ($a)" ;;
      esac
      ;;
  esac
done

exec "$(real rm)" "$@"
"#;

const SUDO_BODY: &str = r#"
deny "sudo"
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_wrapped_command_gets_a_script() {
        for name in WRAPPED {
            let s = script(name);
            assert!(s.starts_with("#!/usr/bin/env bash"), "{name} has no shebang");
            assert!(s.contains("deny()"), "{name} has no deny helper");
        }
    }

    #[test]
    fn sudo_is_refused_outright() {
        assert!(script("sudo").contains("deny \"sudo\""));
    }

    #[test]
    fn the_shim_comes_first_on_the_agent_path() {
        let p = agent_path(Path::new("/data"), "/usr/bin:/bin");
        assert!(p.starts_with("/data/githud/shim:"), "{p}");
    }

    #[test]
    fn repeated_starts_do_not_stack_duplicate_shim_entries() {
        let once = agent_path(Path::new("/data"), "/usr/bin:/bin");
        let twice = agent_path(Path::new("/data"), &once);
        assert_eq!(once, twice);
    }

    #[test]
    fn an_empty_inherited_path_still_yields_the_shim() {
        assert_eq!(agent_path(Path::new("/data"), ""), "/data/githud/shim");
    }

    #[test]
    fn install_writes_executable_wrappers() {
        let tmp = std::env::temp_dir().join(format!("githud-shim-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);

        let dir = install(&tmp).expect("install should succeed");

        for name in WRAPPED {
            let p = dir.join(name);
            assert!(p.is_file(), "{name} missing");
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt as _;
                let mode = std::fs::metadata(&p).unwrap().permissions().mode();
                assert_eq!(mode & 0o111, 0o111, "{name} is not executable");
            }
        }

        // Regenerated every start, so a stale guard cannot survive.
        install(&tmp).expect("reinstall should overwrite");
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
